version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: db_sistema_notas
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: sistema_notas
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: